services:
  - type: web
    name: self-introduction-scorer-api 
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
    
      - key: JAVA_VERSION
        value: 17